[package]
name = "lwms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.105.0"
url = "2.2.2"
tokio = "1.12.0"